### ISSUE TITLE
gulp bug

### ISSUE THREAD

**Issue by teslan** [joelcoxokc/aurelia-interface#49]
C:\a\tut\aurelia-interface>gulp build
and
C:\a\tut\aurelia-interface>gulp watch
module.js:338
    throw err;
          ^
Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\a\tut\aurelia-interface\gulpfile.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by rquast** [comment]
Not that this is a fix, but more of a workaround.. I did an npm install to get around that.
